---
 - name: copying files
   hosts: all
   vars:
           content: "Welcome"
           file: linoop.txt
           directory: /tmp/
   tasks:
           - name: calling variable contents
             ansible.builtin.copy:
                     content: "{{ content }}"
                     dest: "{{ directory }}{{ file }}"
             tags: ['never','akram']
             register: result
           - name: Print return information from the previous task
             ansible.builtin.debug: 
                    vars: result.output


   

