---
- name: Update httpd and restart if needed
  hosts: all
  become: yes

  tasks:
    - name: Update httpd package
      yum:
        name: httpd
        state: latest
      notify: restart httpd

  handlers:

    - name: stop service if started
      ansible.builtin.service:
        name: httpd
        state: restarted


